# Generated by Django 6.0.2 on 2026-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('glb_file', models.FileField(upload_to='models/')),
                ('usdz_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
