# Generated by Django 6.0.2 on 2026-06-13 17:37

import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_scene_delete_model3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='parent',
            field=models.CharField(blank=True, default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='scene',
            name='glb_file',
            field=models.FileField(upload_to=viewer.models.scene_upload_path),
        ),
        migrations.AlterField(
            model_name='scene',
            name='usdz_file',
            field=models.FileField(blank=True, null=True, upload_to=viewer.models.scene_upload_path),
        ),
    ]
