# Generated by Django 6.0.2 on 2026-07-01 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_feedback_response_delete_userregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='ar_scale',
            field=models.CharField(choices=[('auto', 'Auto (model-viewer scales to fit the space)'), ('fixed', 'Fixed (real-world scale — 1 glTF unit = 1 metre)')], default='fixed', help_text="'fixed' places the model at real-world scale (1 glTF unit = 1 m). Use this for dishes/objects whose physical size matters. 'auto' lets Scene Viewer/Quick Look scale it to fit — useful when the GLB's native units are wrong and you can't re-export.", max_length=10),
        ),
        migrations.AddField(
            model_name='scene',
            name='environment_image',
            field=models.CharField(blank=True, choices=[('neutral', 'Neutral studio'), ('legacy', 'Legacy (warm, pre-v4 default)')], default='neutral', help_text='Named environment preset used for IBL (image-based lighting). Leave blank to use environment_image_url instead.', max_length=20),
        ),
        migrations.AddField(
            model_name='scene',
            name='environment_image_url',
            field=models.URLField(blank=True, help_text='URL to a custom HDR/EXR environment map. Takes precedence over environment_image if set.'),
        ),
        migrations.AddField(
            model_name='scene',
            name='exposure',
            field=models.FloatField(default=1.0, help_text="Overall brightness multiplier for the 3D viewer. 1.0 = default. Raise for dim models, lower for blown-out ones. Has no effect inside Scene Viewer or Quick Look AR — those use the device's own light estimation.", validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AddField(
            model_name='scene',
            name='shadow_intensity',
            field=models.FloatField(default=1.0, help_text='Contact shadow strength beneath the model. 0 = none, 1 = default, 2 = very dark.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='scene',
            name='shadow_softness',
            field=models.FloatField(default=1.0, help_text='Shadow edge blur. 0 = hard edge, 1 = fully soft.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='scene',
            name='tone_mapping',
            field=models.CharField(choices=[('neutral', 'Neutral (Khronos PBR — accurate colours, good for food)'), ('aces', 'ACES (cinematic, slightly warm/contrasty)'), ('agx', 'AgX (natural, handles blown highlights well)'), ('linear', 'Linear (no tone mapping — raw output)'), ('commerce', 'Commerce (Khronos variant tuned for product shots)')], default='neutral', help_text="Tone mapping operator used to convert HDR → display range. 'neutral' is the Khronos PBR standard and is the right default for food/product shots.", max_length=20),
        ),
        migrations.AddField(
            model_name='scene',
            name='webxr_model_scale',
            field=models.FloatField(default=1.0, help_text='Extra scale multiplier applied on top of bounding-box normalisation in the custom WebXR tap-to-place viewer (WebXRPlacementViewer). The viewer normalises the model to ~25 cm by default; set this to e.g. 1.5 to make a specific dish appear 50% larger in AR. Has no effect on the model-viewer / Scene Viewer / Quick Look paths.', validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
