# Generated by Django 6.0.2 on 2026-07-19 08:58

import viewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_scene_ar_scale_scene_environment_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='mind_target',
            field=models.FileField(blank=True, help_text="Compiled MindAR .mind target file for the image-tracking AR fallback, generated from a marker image via MindAR's compiler: https://hiukim.github.io/mind-ar-js-doc/tools/compile", null=True, upload_to=viewer.models.scene_upload_path),
        ),
    ]
