# Generated by Django 6.0.4 on 2026-06-14 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_userlogin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLogin',
            new_name='UserRegister',
        ),
    ]
