# Generated by Django 6.0.7 on 2026-07-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_migrate_scene_data_to_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scene',
        ),
    ]