# Generated by Django 6.0.2 on 2026-06-15 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_scene_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='owner',
        ),
        migrations.AlterField(
            model_name='scene',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
