# Generated by Django 6.0.4 on 2026-07-11 09:03

import dashboardMenu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='created_at',
            new_name='joined_at',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('premium', 'Premium')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=dashboardMenu.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to=dashboardMenu.models.dish_glb_path),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to=dashboardMenu.models.dish_image_path),
        ),
        migrations.AlterField(
            model_name='dish',
            name='starting_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dish',
            name='usdz_file',
            field=models.FileField(blank=True, null=True, upload_to=dashboardMenu.models.dish_glb_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=dashboardMenu.models.restaurant_logo_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#FFC200', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
