# Generated by Django 6.0.2 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0002_rename_name_restaurant_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('Lite Menu', 'Lite Menu'), ('Standard Menu', 'Standard Menu'), ('Pro Menu', 'Pro Menu')], default='Standard Menu', max_length=20),
        ),
    ]
