# Generated by Django 6.0.2 on 2026-07-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0003_alter_restaurant_city_alter_restaurant_owner_name_and_more'),
        ('dashboardMenu', '0003_dish_ar_scale_dish_environment_image_and_more'),
    ]

    operations = [
    ]
