# Generated by Django 6.0.2 on 2026-07-24 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0004_merge_20260724_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
