# Generated by Django 6.0.2 on 2026-07-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0005_alter_dish_id'),
        ('dashboardMenu', '0006_dish_uuid_step3_swap_pk'),
    ]

    operations = [
    ]
