# Generated by Django 6.0.7 on 2026-07-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0008_migrate_dish_mind_target_to_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='mind_target',
        ),
    ]