# Generated by Django 6.0.2 on 2026-07-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardMenu', '0007_merge_0005_alter_dish_id_0006_dish_uuid_step3_swap_pk'),
        ('dashboardMenu', '0009_remove_dish_mind_target'),
    ]

    operations = [
    ]
